---
# tasks file for dhcp

- name: Setup nginx
  include_tasks: nginx.yaml

- name: Install DHCP package
  ansible.builtin.package:
    name: isc-dhcp-server
    state: latest

- name: Get Local IP
  shell: |
    set -o pipefail
    ip --json addr show eth0 | jq -r '.[0].addr_info[] | select(.family == "inet") | .local'
  args:
    executable: /bin/bash
  register: local_ip

- name: Copy DHCP config
  ansible.builtin.template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf

- name: Restart DHCP service
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted