---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Copy ztp.py to /var/www/html/ztp.py
  copy:
    src: ztp.py
    dest: /var/www/html/ztp.py
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes