---
- name: Show CDP
  include_role:
    name: common
    tasks_from: show_cdp
  vars:
    return_output: show_cdp
  when: inventory_hostname != "localhost"

- name: "Prepare Interface L2"
  include_role:
    name: common
    tasks_from: prepare_interface_l2
  vars:
    interface: "{{ item.LOCAL_INTERFACE }}"
  with_items: "{{ show_cdp }}"
  when: inventory_hostname != "localhost" and item.NEIGHBOR_NAME == "FR_TLS_R1.mydomain.com" or item.NEIGHBOR_NAME == "FR_TLS_R2.mydomain.com" or item.NEIGHBOR_NAME == "FR_TLS_R3.mydomain.com"

- name: "Set all interfaces as trunk"
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.LOCAL_INTERFACE }}"
        trunk:
          allowed_vlans: 310-320
          encapsulation: dot1q
        mode: trunk
    state: replaced
  with_items: "{{ show_cdp }}"
  when: inventory_hostname != "localhost" and item.NEIGHBOR_NAME == "FR_TLS_R1.mydomain.com" or item.NEIGHBOR_NAME == "FR_TLS_R2.mydomain.com" or item.NEIGHBOR_NAME == "FR_TLS_R3.mydomain.com"

- name: "Create VLANs"
  include_tasks: vlan.yml
  when: inventory_hostname != "localhost"

- name: "Interfaces Configuration"
  include_tasks: ints.yml
  when: inventory_hostname != "localhost"