---
# defaults file for bgp

subnet: 10.33.88.240/28
routers:
  Router_14:
    ints:
      - Gig0/1
    networks: 10.33.88.241
    neighbors:
      - address: 10.33.88.242
        remote_as: 65002
    asn: 65001
    eigrp: 1
  Router_15:
    ints:
      - Gig0/1
    networks: 10.33.88.242
    neighbors:
      - address: 10.33.88.241
        remote_as: 65001
    asn: 65002
    eigrp: 2