---
# defaults file for bgp

subnet: 10.33.88.240/28
routers:
  Router_14:
    ints:
      - Gig0/1
    networks:
      - address: 10.33.88.242
    neighbors:
      - address: 10.33.88.243
        description: merge neighbor
        remote_as: 65002
    asn: 65001
  Router_15:
    ints:
      - Gig0/1
    networks:
      - address: 10.33.88.243
    neighbors:
      - address: 10.33.88.242
        description: merge neighbor
        remote_as: 65001
    asn: 65002