---

- name: "Default interface configuration"
  cisco.ios.ios_config:
    lines:
      - "default interface {{ interface }}"

- name: "Set encapsulation"
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ interface }}"
        trunk:
          encapsulation: dot1q
    state: merged