---

- name: No switchport
  cisco.ios.ios_config:
    lines:
      - no switchport
    parents: interface {{ item }}
  with_items: "{{ routers[inventory_hostname].ints }}"
  when: inventory_hostname != "localhost"

- name: "Set Interface"
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item }}"
        ipv4:
          - address: "{{ subnet | ansible.utils.ipmath(groups['eigrp'].index(inventory_hostname) + 1) }}/{{ subnet | ansible.utils.ipaddr('prefix') }}"
  with_items: "{{ routers[inventory_hostname].ints }}"
  when: inventory_hostname != "localhost"

- name: Reset EIGRP
  cisco.ios.ios_config:
    lines:
      - no router eigrp {{ routers[inventory_hostname].name }}
  when: inventory_hostname != "localhost"

- name: Set EIGRP Networks
  cisco.ios.ios_config:
    lines:
      - address-family ipv4 unicast autonomous-system {{ routers[inventory_hostname].asn }}
      - network {{ item | ansible.utils.ipaddr('address') }} {{ item | ansible.utils.ipaddr('netmask') }}
    parents: router eigrp {{ routers[inventory_hostname].name }}
  with_items: "{{ routers[inventory_hostname].networks }}"
  when: inventory_hostname != "localhost"

- name: Debug Routers
  debug:
    var: "{{ item.value.asn }}"
  with_items: "{{ routers | dict2items }}"
  when: inventory_hostname != "localhost"